package uz.nuriddin.springtasknuriddin


enum class ErrorCode(val code: Int) {
    USERNAME_EXISTS(100),
    USER_NOT_FOUND(101),
    USER_PAYMENT_TRANSACTION_NOT_FOUND(102),
    CATEGORY_NOT_FOUND(103),
    PRODUCT_NOT_FOUND(104),
    PRODUCT_IS_NOT_ENOUGH(105),
    BALANCE_IS_NOT_ENOUGH(106),
    TRANSACTION_NOT_FOUND(107)
}